---
podman_enabled: true

podman_apps:
  jellyfin:
    enabled: true
    image: ghcr.io/jellyfin/jellyfin
    # renovate: datasource=docker depName=ghcr.io/jellyfin/jellyfin
    tag: 10.11.9
    port: 8096
    network_mode: host
    tmpfs:
      - /cache
    volumes:
      - /opt/jellyfin/config:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tv:/tv
      - /mnt/media/music:/music
      - /mnt/media/youtube:/youtube
    devices:
      - /dev/dri/renderD128
      - /dev/dri/card0
    env:
      TZ: Europe/London
