---
podman_enabled: true

podman_apps:
  pulse:
    enabled: false
    image: ghcr.io/rcourtman/pulse
    # renovate: datasource=docker depName=ghcr.io/rcourtman/pulse
    tag: 5.1.31
    port: 7655
    volumes:
      - /opt/pulse:/data
    env:
      TZ: Europe/London
