---
- name: Check container status
  ansible.builtin.command:
    cmd: "pct status {{ pve_lxc_vmid }}"
  register: _pve_lxc_status
  changed_when: false
  failed_when: false
  delegate_to: "{{ pve_lxc_proxmox_node }}"
  tags: [always]

- name: Store container running state
  ansible.builtin.set_fact:
    _pve_lxc_was_running: "{{ 'running' in _pve_lxc_status.stdout }}"
  when: _pve_lxc_status.rc == 0
  tags: [always]

- name: Stop container if running
  ansible.builtin.command:
    cmd: "pct stop {{ pve_lxc_vmid }}"
  when:
    - _pve_lxc_status.rc == 0
    - _pve_lxc_was_running | default(false) | bool
  delegate_to: "{{ pve_lxc_proxmox_node }}"
  changed_when: true
  tags: [stop]

- name: Remove device passthrough
  ansible.builtin.include_tasks: remove_device_item.yml
  loop: "{{ pve_lxc_devices }}"
  loop_control:
    loop_var: device
    index_var: device_idx
  tags: [device, passthrough]

- name: Start container if it was running
  ansible.builtin.command:
    cmd: "pct start {{ pve_lxc_vmid }}"
  when:
    - _pve_lxc_status.rc == 0
    - _pve_lxc_was_running | default(false) | bool
    - pve_lxc_device_auto_restart | bool
  delegate_to: "{{ pve_lxc_proxmox_node }}"
  changed_when: true
  tags: [start]
