---
# AAH site variables

site_code: aah
site_domain: aah.muffn.io
site_nameservers:
  - 10.82.7.102
site_search_domains:
  - aah.muffn.io
  - lcy.muffn.io
  - lgy.muffn.io
  - internal.muffn.io # Legacy - needs to be migrated from
site_ntp_enabled: true
site_ntp_servers:
  - 10.82.2.1
