---
# LCY site variables

site_code: lcy
site_domain: lcy.muffn.io
site_nameservers:
  - 10.83.7.102
site_search_domains:
  - lcy.muffn.io
  - aah.muffn.io
  - lgy.muffn.io
  - internal.muffn.io # Legacy - needs to be migrated from
site_ntp_enabled: true
site_ntp_servers:
  - 10.83.2.1
