---
pve_lxcs_wgtun01:
  wgtun01:
    vmid: 117
    hostname: wgtun01.aah.muffn.io
    node: pve04
    cores: 4
    memory: 4096
    swap: 512
    disk: "32G"
    network_ip: "10.82.10.117/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    runtime: podman
    tags:
      - ansible
      - site_aah
      - app_wgtun
      - podman_app
    features: "{{ lxc_features_podman }}"
    devices:
      - path: /dev/net/tun
    bind_mounts:
      - host_path: /mnt/scratch/downloads/torrents
        lxc_path: /mnt/incomplete
        shared: true
      - host_path: /mnt/aah-fs02/torrent-downloads
        lxc_path: /mnt/downloads
        shared: true
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
