---
pve_lxcs_immich_ml01:
  immich-ml01:
    vmid: 137
    hostname: immich-ml01.aah.muffn.io
    node: pve02
    cores: 6
    memory: 8192
    swap: 512
    disk: "16G"
    storage: "local-zfs"
    network_ip: "10.82.10.137/24"
    network_gw: "10.82.10.1"
    network_vlan: 710
    unprivileged: true
    tags:
      - ansible
      - os_linux
      - os_trixie
      - site_aah
      - podman_app
      - app_immich
    features:
      nesting: true
      keyctl: true
    devices:
      - path: /dev/dri/renderD128
        mode: "0666"
      - path: /dev/dri/card0
        mode: "0666"
