---
pve_lxcs_qdev01:
  qdev01:
    vmid: 100
    hostname: qdev01.aah.muffn.io
    node: pve02
    cores: 1
    memory: 512
    swap: 0
    disk: "4G"
    storage: "local-lvm"
    network_ip: "10.82.2.149/24"
    network_gw: "10.82.2.1"
    network_bridge: "vmbr1"
    network_vlan: 702
    unprivileged: true
    onboot: true
    tags:
      - ansible
      - site_aah
      - app_qdevice
    features:
      nesting: true
      keyctl: false
