---
podman_enabled: true

podman_apps:
  radarr:
    enabled: true
    image: ghcr.io/home-operations/radarr
    # renovate: datasource=docker depName=ghcr.io/home-operations/radarr
    tag: 6.4.0.10523
    port: 7878
    uid: 65534
    gid: 65533
    volumes:
      - /opt/radarr:/config
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
    env:
      TZ: Europe/London
