---
site_domain: ""
site_nameservers: []
site_search_domains: []
site_ntp_servers: []
site_ntp_enabled: true

pve_system_hostname: ""
pve_system_domain: "{{ site_domain }}"

pve_system_hosts_ip: ""

pve_system_cluster_peers: []
pve_system_timezone: ""

pve_system_locale: "en_US.UTF-8"
pve_system_locale_generate:
  - "en_US.UTF-8 UTF-8"

pve_system_nameservers: "{{ site_nameservers }}"
pve_system_search_domains: "{{ site_search_domains }}"

pve_system_ntp_servers: "{{ site_ntp_servers }}"
pve_system_ntp_fallback_servers:
  - "time.cloudflare.com"
pve_system_ntp_enabled: "{{ site_ntp_enabled }}"

pve_system_ssh_permit_root_login: "prohibit-password"
pve_system_ssh_password_authentication: false
pve_system_ssh_port: 22

pve_system_ssh_import_keys_url: ""
pve_system_ssh_import_keys_user: "root"

pve_system_motd_enabled: false
pve_system_motd_content: ""

# Sysctl
# perf_event_paranoid: 2 = default, allows CAP_PERFMON for LXC with Intel GPU stats
pve_system_perf_event_paranoid: 2
