---
- name: Configure perf_event_paranoid
  ansible.posix.sysctl:
    name: kernel.perf_event_paranoid
    value: "{{ pve_system_perf_event_paranoid }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-frigate.conf
    reload: true
  when: pve_system_perf_event_paranoid is defined
  tags:
    - sysctl
    - perf
