variable "cloudflare_api_token" {
  type      = string
  sensitive = true
}

variable "cloudflare_account_id" {
  type = string
}

variable "technitium_aah_server_url" {
  type    = string
  default = "https://10.82.7.102"
}

variable "technitium_aah_api_token" {
  type      = string
  sensitive = true
}

# lxc_dns_records is auto-generated by ops/gen_lxc_dns.py at deploy time.
# Do not define or edit tf/lxc_dns.auto.tfvars.json manually.
variable "lxc_dns_records" {
  type = list(object({
    name = string
    zone = string
    ip   = string
  }))
  default = []
}
