---
podman_enabled: true

podman_apps:
  seerr:
    enabled: true
    image: ghcr.io/seerr-team/seerr
    # renovate: datasource=docker depName=ghcr.io/seerr-team/seerr
    tag: v3.3.0
    container_name: Seerr
    port: 5055
    uid: 1000
    gid: 1000
    user: 1000:1000
    volumes:
      - /opt/seerr:/app/config
    env:
      TZ: Europe/London
