---
pve_lxcs_mcphub01:
  mcphub01:
    vmid: 120
    hostname: mcphub01.lcy.muffn.io
    cores: 2
    memory: 2048
    swap: 512
    disk: "16G"
    network_ip: "10.83.7.120/24"
    network_gw: "10.83.7.1"
    network_vlan: 7
    unprivileged: true
    tags:
      - ansible
      - os_linux
      - os_trixie
      - site_lcy
      - podman_app
      - app_mcphub
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
