---
# Deploy Sonarr into its LXC using rootful Podman + system Quadlet

- name: Deploy Sonarr
  hosts: tag_sonarr01
  become: true
  gather_facts: true

  roles:
    - role: podman
      tags:
        - podman
    - role: apps/podman/sonarr
      tags:
        - sonarr
        - podman
        - lxc_app
