---
# Deploy Radarr into its LXC using rootful Podman + system Quadlet

- name: Deploy Radarr
  hosts: tag_radarr01
  become: true
  gather_facts: true

  roles:
    - role: podman
      tags:
        - podman
    - role: apps/podman/radarr
      tags:
        - radarr
        - lxc_app
