---
podman_enabled: true

podman_apps:
  tautulli:
    enabled: true
    image: ghcr.io/home-operations/tautulli
    # renovate: datasource=docker depName=ghcr.io/home-operations/tautulli
    tag: 2.17.1
    port: 8181
    uid: 65534
    gid: 65533
    volumes:
      - /opt/tautulli:/config
    env:
      TZ: Europe/London
