---
podman_enabled: true

podman_volumes:
  model-cache:
    driver: local

podman_apps:
  immich-ml:
    enabled: true
    image: ghcr.io/immich-app/immich-machine-learning
    # renovate: datasource=docker depName=ghcr.io/immich-app/immich-machine-learning versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-openvino$
    tag: v3.0.1-openvino
    port: 3003
    volumes:
      - model-cache:/cache
    devices:
      - /dev/dri/renderD128
    env:
      IMMICH_LOG_LEVEL: debug
      MPLCONFIGDIR: /tmp/matplotlib
      MACHINE_LEARNING_OPENVINO_PRECISION: FP16
      MACHINE_LEARNING_MODEL_TTL: "0"
      MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL: ViT-SO400M-16-SigLIP2-384__webli
      MACHINE_LEARNING_PRELOAD__CLIP__VISUAL: ViT-SO400M-16-SigLIP2-384__webli
      # Pin thread counts to LXC cores // disable ORT affinity in cgroup
      MACHINE_LEARNING_REQUEST_THREADS: "6"
      MACHINE_LEARNING_MODEL_INTRA_OP_THREADS: "2"
      MACHINE_LEARNING_MODEL_INTER_OP_THREADS: "1"
      MACHINE_LEARNING_WORKER_TIMEOUT: "600"
      ORT_DISABLE_THREAD_AFFINITY: "1"
      OMP_NUM_THREADS: "6"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      KMP_AFFINITY: "disabled"
      OMP_PROC_BIND: "false"
