---
pve_lxcs_collector01:
  collector01:
    vmid: 157
    hostname: collector01.aah.muffn.io
    node: pve04
    cores: 2
    memory: 1024
    swap: 512
    disk: "16G"
    storage: "local-zfs"
    network_ip: "10.82.7.157/24"
    network_gw: "10.82.7.1"
    network_vlan: 707
    unprivileged: true
    onboot: true
    start: true
    tags:
      - ansible
      - os_linux
      - os_trixie
      - site_aah
      - podman_app
      - app_collector
    features: "{{ lxc_features_podman }}"
    ha: "{{ lxc_ha_default }}"
    replication: "{{ lxc_replication_default }}"
