---
podman_enabled: true

podman_apps:
  prowlarr:
    enabled: true
    image: ghcr.io/home-operations/prowlarr
    # renovate: datasource=docker depName=ghcr.io/home-operations/prowlarr
    tag: 2.5.2.5483
    port: 9696
    uid: 65534
    gid: 65533
    volumes:
      - /opt/prowlarr:/config
    env:
      TZ: Europe/London
