---
podman_enabled: true

podman_apps:
  beszel:
    enabled: true
    image: ghcr.io/henrygd/beszel/beszel
    # renovate: datasource=docker depName=ghcr.io/henrygd/beszel/beszel
    tag: "0.19.0"
    port: 8090
    volumes:
      - /opt/beszel:/beszel_data
    env:
      DISABLE_PASSWORD_AUTH: true
      USER_CREATION: "true"
      TZ: Europe/London
