---
wgtun_config_dir: /opt/wgtun
wgtun_gluetun_apikey: ""
wgtun_qbittorrent_uid: 65534
wgtun_qbittorrent_gid: 65534
wgtun_qbittorrent_state_dir: "{{ wgtun_config_dir }}/qbittorrent/qBittorrent"
wgtun_qbittorrent_cache_dir: "{{ wgtun_config_dir }}/qbittorrent/.cache/qBittorrent"
wgtun_qbittorrent_altui_enabled: true
# renovate: datasource=github-releases depName=VueTorrent/VueTorrent
wgtun_qbittorrent_altui_version: v2.33.0
wgtun_qbittorrent_altui_dir_host: "{{ wgtun_config_dir }}/qbittorrent/vuetorrent"
wgtun_qbittorrent_altui_dir_container: /config/vuetorrent
wgtun_qbittorrent_host_header_validation: false
wgtun_qbittorrent_auth_subnet_whitelist_enabled: false
wgtun_qbittorrent_auth_subnet_whitelist: ""
