---
podman_enabled: true

podman_apps:
  sonarr:
    enabled: true
    image: ghcr.io/home-operations/sonarr
    # renovate: datasource=docker depName=ghcr.io/home-operations/sonarr
    tag: 4.0.18.2978
    port: 8989
    uid: 65534
    gid: 65533
    volumes:
      - /opt/sonarr:/config
      - /mnt/tv:/tv
      - /mnt/downloads:/downloads
    env:
      TZ: Europe/London
