---
github_runner_user: github-runner
github_runner_home: /opt/github-runner
github_runner_version: latest
github_runner_repo: ""
github_runner_pat: ""
github_runner_vault_password: ""
github_runner_git_crypt_key: ""
github_runner_labels: []
github_runner_name: "{{ inventory_hostname }}"
github_runner_group: Default
