#!/usr/bin/env python3
"""Build roles/apps/collector/files/snmp_modules.yml.static from the upstream snmp_exporter definitions.

Alloy's built-in SNMP modules (if_mib, mikrotik, ...) are only available with
the default `public` community. With a private community Alloy needs its own
snmp.yml, so the collector role ships the modules below, copied unchanged from
the upstream snmp.yml and trimmed to what SwOS switches answer.

    curl -fsSLO https://raw.githubusercontent.com/prometheus/snmp_exporter/v0.29.0/snmp.yml
    python3 ops/snmp/build_modules.py snmp.yml > ansible/roles/apps/collector/files/snmp_modules.yml.static

Alloy 1.20.1 embeds snmp_exporter v0.29.0; use the same tag. To support another
platform (RouterOS switches with CPU, memory and PoE), add a module pair to
MODULES below, named <platform>_interfaces and <platform>_health.
"""
import copy
import sys

import yaml

# IF-MIB columns walked for the interface module, so the switch is not asked
# for whole tables.
IF_COLUMNS = [
    "2.2.1.2", "2.2.1.7", "2.2.1.8", "2.2.1.9", "2.2.1.13", "2.2.1.14", "2.2.1.19", "2.2.1.20",
    "31.1.1.1.1", "31.1.1.1.6", "31.1.1.1.7", "31.1.1.1.8", "31.1.1.1.9", "31.1.1.1.10",
    "31.1.1.1.11", "31.1.1.1.12", "31.1.1.1.13", "31.1.1.1.15", "31.1.1.1.18",
]

MODULES = {
    "swos_interfaces": {
        "walk": ["1.3.6.1.2.1." + c for c in IF_COLUMNS],
        "metrics": [
            ("if_mib", n)
            for n in (
                "ifAdminStatus", "ifOperStatus", "ifLastChange", "ifHighSpeed",
                "ifInErrors", "ifOutErrors", "ifInDiscards", "ifOutDiscards",
                "ifHCInOctets", "ifHCOutOctets", "ifHCInUcastPkts", "ifHCOutUcastPkts",
                "ifHCInMulticastPkts", "ifHCOutMulticastPkts", "ifHCInBroadcastPkts", "ifHCOutBroadcastPkts",
            )
        ],
    },
    "swos_health": {
        # system group, MikroTik health (mtxrHl, mtxrGauge) and optical (SFP) tables
        "walk": ["1.3.6.1.2.1.1", "1.3.6.1.4.1.14988.1.1.3", "1.3.6.1.4.1.14988.1.1.19"],
        "metrics": [("system", n) for n in ("sysDescr", "sysUpTime", "sysName")]
        + [
            ("mikrotik", n)
            for n in (
                "mtxrHlProcessorTemperature", "mtxrHlPowerSupplyState", "mtxrHlBackupPowerSupplyState",
                "mtxrGaugeValue",
                "mtxrOpticalRxLoss", "mtxrOpticalTxFault", "mtxrOpticalWavelength", "mtxrOpticalTemperature",
                "mtxrOpticalSupplyVoltage", "mtxrOpticalTxBiasCurrent", "mtxrOpticalTxPower", "mtxrOpticalRxPower",
            )
        ],
    },
}


def main(path):
    with open(path) as f:
        upstream = yaml.safe_load(f)["modules"]
    out = {}
    for name, spec in MODULES.items():
        by_module = {}
        metrics = []
        for module, metric in spec["metrics"]:
            by_module.setdefault(module, {m["name"]: m for m in upstream[module]["metrics"]})
            metrics.append(copy.deepcopy(by_module[module][metric]))
        out[name] = {"walk": spec["walk"], "metrics": metrics}
    print("# Generated by ops/snmp/build_modules.py from snmp_exporter v0.29.0; do not edit by hand.")
    print("# Modules for MikroTik SwOS switches. The collector role adds the `auths` block.")
    yaml.safe_dump({"modules": out}, sys.stdout, sort_keys=False)


if __name__ == "__main__":
    main(sys.argv[1])
