name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.example.*"
      - "**/*.example"
  workflow_dispatch:

jobs:
  dispatch:
    name: Ansible dispatch
    runs-on: [self-hosted, linux, aah]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run dispatch
        run: bash ops/run_dispatch.sh
