---
- name: Install base packages
  ansible.builtin.package:
    name: >-
      {{
        (
          linux_base_packages
          + linux_base_extra_packages
          + (
            linux_base_manage_qemu_guest_agent | bool
            | ternary([linux_base_qemu_guest_agent_package], [])
          )
          + (
            (ansible_distribution_major_version | int >= 13)
            | ternary(linux_base_packages_debian_13, [])
          )
        ) | unique
      }}
    state: present

- name: Check if iGPU device is present
  ansible.builtin.stat:
    path: /dev/dri/renderD128
  register: _linux_base_igpu_device

- name: Install iGPU packages
  ansible.builtin.package:
    name: "{{ linux_base_igpu_packages }}"
    state: present
  when: _linux_base_igpu_device.stat.exists
