---
podman_enabled: true

podman_apps:
  rembg:
    enabled: true
    image: danielgatis/rembg
    # renovate: datasource=docker depName=danielgatis/rembg
    tag: 2.0.77
    port: 37285
    container_port: 7000
    exec: s
    volumes:
      - /opt/rembg/models:/root/.u2net
    env:
      MODEL: birefnet-general-lite
      OMP_NUM_THREADS: "4"
      TZ: Europe/London
